---
abstract: 'distributed locks via ZooKeeper'
author:
  - 'Yury Zavarin <yury.zavarin@gmail.com>'
build_requires:
  IO::Handle: 0
  POSIX: 0
  Test::Class: 0
  Test::More: 0
  Time::HiRes: 0
  parent: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-ZooKeper-Lock
requires:
  Net::ZooKeeper: 0
  Params::Validate: 0
resources:
  homepage: http://github.com/tadam/Net-ZooKeeper-Lock
  repository: git://github.com/tadam/Net-ZooKeeper-Lock.git
version: 0.01
